# Generated by Django 4.2.2 on 2023-06-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_in_video', models.TextField()),
                ('custom_text', models.BooleanField()),
                ('video_duration', models.PositiveIntegerField()),
                ('custom_duration', models.BooleanField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('video_filename', models.TextField()),
            ],
        ),
    ]
